### ISSUE TITLE
Database not listed

### ISSUE THREAD

**Issue by BacchusA** [TomFrankly/pipedream-notion-recurring-tasks#12]
How do I fix my database not being listed? I see the default All Tasks [UBCC] but I changed the name of that database. I tried entering the  database ID but it could not be found. Help?

**Comment by RemyMachado** [comment]
I had a similar issue with the database not showing. Once I disconnected my Notion account from Pipedream and went through the procedure again it finally appeared. Also, the correct access rights must have been granted during the login process.

**Comment by TomFrankly** [comment]
@BacchusA this can happen on rare ocassions due to general finnickiness in the Notion API's auth functions.

Typically, the easiest way to fix it is to navigate directly to your database. Then go to the ••• menu and see if Pipedream is listed under Connections.

If it isn't, add it from Add Connections. If it is, try Disconnecting it, then adding it back from Add Connections manually.

![CleanShot 2024-04-20 at 16 31 19@2x](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/684961/be27bb63-18bb-4d78-9fa1-262e15397106)

I've been chatting with the Notion API team about this issue – it's rare, but annoying!
