### ISSUE TITLE
Due date and time

### ISSUE THREAD

**Issue by MuhammadSami-art** [TomFrankly/pipedream-notion-recurring-tasks#19]
Hi Thomas,
My workflow is going smoothly, but there's an issue with time tracking. When I update the due date for tasks with a time duration, the duration information gets cleared.
I would like the time estimate to remain unchanged when the due date is updated. Is there a way to achieve this?
@TomFrankly

**Comment by TomFrankly** [comment]
@MuhammadSami-art can you share more detail? Are you just talking about the end date?

If so, we might be able to support it – but I can't guarantee it. I don't remember all the details, but I know we ran into issues trying to support dates with start and end times, as well as times in general. I know it has to do with really technical, annoying issues with timezones, daylight savings time, and Notion API limitations.

**Comment by MuhammadSami-art** [comment]
These are screenshots of before and after recurring tasks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TomFrankly** [comment]
@MuhammadSami-art I'm not seeing any screenshots here – just this: 
![CleanShot 2024-07-25 at 09 04 22@2x](https://github.com/user-attachments/assets/98815f91-b3f1-4e3d-8a25-78f53eee0e44)

If you copy a screenshot to your clipboard, you can paste it directly here in Github.

**Comment by MuhammadSami-art** [comment]
@TomFrankly
There's an issue pasting a screenshot.

The problem occurs when I input a due date with an end date and start and end times. After pressing the "done" button to complete the task, the recurring task workflow starts, and the due date changes to the next due date while the end date and end & start time are cleared.

I hope you understand the issue dear thomas.

**Comment by TomFrankly** [comment]
@MuhammadSami-art alright, was able to look into this just now.

End dates should work, and I just tested on my own automation to double-check that: 

<img width="629" alt="CleanShot 2024-07-25 at 12 11 13@2x" src="https://github.com/user-attachments/assets/a2d7d8f8-485b-48fa-9b4e-05dc039c51c0">

If your end dates don't work even after removing times, you may need to update the workflow: https://thomasjfrank.com/notion-automated-recurring-tasks/#update - and also make sure you have the latest formulas in your template, found here: https://thomasjfrank.com/notion-automated-recurring-tasks/#faqs-and-reference-guides (if you have any version of Ultimate Brain or Ultimate Tasks released after mid-2023, you should have these).

We can't yet support times on recurring tasks due to Daylight Saving Time rules—Notion won't communicate a user's location due to privacy concerns, so we can't effectively get their DST information. Even if we asked users for zip/city/state/country at the Pipedream level, it wouldn't account for travel, since Notion automatically detects your time zone, and Pipedream wouldn't know to use the new time zone rules temporarily.

As it stands, the time would be incorrect for any tasks that recur after a DST-change date (e.g., a quarterly company meeting may have the wrong time set, which could be unfortunate), so we decided not to include it for now, since it wouldn't be 100% reliable.

**Comment by MuhammadSami-art** [comment]
Thanks a lot for your kind help
