### ISSUE TITLE
Hi, Recurring Tasks Issue Screenshots

### ISSUE THREAD

**Issue by Davca14** [TomFrankly/pipedream-notion-recurring-tasks#6]
I took screenshots as a starting point. If you need any additional info. let me know.
![1](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/157522034/55c0c2c9-fdae-4edf-a346-854f70c630d7)
![2](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/157522034/15bb2882-00a3-4c7e-ac2b-5e2d408faf2c)
![3](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/157522034/12354062-791f-47c8-8ca5-1a36aacc1dfa)
![4](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/157522034/050cbf0a-fcee-436a-bf48-42957a5f1cc3)
![5](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/157522034/15953ac6-c1da-4919-a095-a047afb2528a)
![7](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/157522034/27e5a4d2-2ac2-491c-a043-09ab6440d94c)

**Comment by aholroyde** [comment]
This is what I am seeing to!

**Comment by TomFrankly** [comment]
@Davca14 I believe this is happening because you've chosen "Next Due" in the "Next Due API" setting.

Next Due API is actually a separate property. If your tasks database doesn't have it, you'll need to create it and add this formula code:

```
if(test(prop("Next Due"), "Error") or empty(prop("Next Due")) or prop("Next Due") == false, "∅", "{\"start\":\"" + formatDate(dateStart(prop("Next Due")), "YYYY-MM-DD") + "\",\"end\":\"" + formatDate(dateEnd(prop("Next Due")), "YYYY-MM-DD") + "\"}")
```

Here's a reference if you need more detail: https://thomasjfrank.com/notion-automated-recurring-tasks/#formulas-and-properties – in the video there, you can see me create that property.

@aholroyde I'm guessing this is your issue as well!

**Comment by Davca14** [comment]
Thank you so much, and I'm sorry not seeing before.
![Screenshot (505)](https://github.com/TomFrankly/pipedream-notion-recurring-tasks/assets/157522034/03b296d5-8b76-4143-a366-055a47d3e0f9)

**Comment by TomFrankly** [comment]
@Davca14 no worries! This is good feedback; I'll push an update that explicitly looks for formulas that contain the code that Next Due API needs to have.
